### ISSUE TITLE
subcontent id function does not generate a UUID

### ISSUE THREAD

**Issue by otacke** [thivinanandh/pdf_to_h5p_converter#1]
https://github.com/thivinanandh/pdf_to_h5p_converter/blob/5c1d9b96a2281984ebd01badacfa71ce17e02fae/generateh5p.py#L79

H5P does not use a completely random subcontent id, but a UUID. A UUID follows a special format scheme. Position 13 and 17 have particular meanings and only hexadecimal values are part of the alphabet, see e.g. https://en.m.wikipedia.org/wiki/Universally_unique_identifier

You can compare your code to how H5P generates subcontent ids/UUIDs at https://github.com/h5p/h5p-php-library/blob/b9058680c386f0faed59eca44e5a618e8ace6218/js/h5p.js#L2286-L2296 Your code does ignore the specific meaning of position 13 and 17 and uses way more values in the alphabet (`0123456789abcdefghijklmnopqrstuvwxyz` instead of `0123456789abcdef`).

Your code does very often generate subcontent ids that are not valid. Even though this might not be harmful for the content, that subcontent id/UUID is used for xAPI statements and Learning Record Stores may (or should) reject statements that contain invalid pseudo UUIDs.

**Comment by thivinanandh** [comment]
Hi Oliver ,

Thanks a lot for pointing that out, i m very new to h5p format and that's
why i might have overlooked it. I will go through the docs you have shared
and will update the code to generate proper uuid..

Again, Thanks a lot for pointing it out.


Thanks
Thivin

**Comment by otacke** [comment]
@thivinanandh No reason to be justify yourself :-) For your convenience, I created a fix and created a [pull request](https://github.com/thivinanandh/pdf_to_h5p_converter/pull/2). Python provides a module that can generate UUIDs, so there's no need to come up with a custom function unless you want to.

**Comment by thivinanandh** [comment]
Hi Oliver,

I have one more query, the image files that were being saved in h5p also
have a hash id added to its end.

Like : image-Lect02-CompArchi-01.png
--> image-Lect02-CompArchi-01-hWctf6sc.png

What kind of logic is being used while adding these hashes to the image
name..

Is it a random UUID cropped to first 8 characters or is there some other
logic  I need to follow..


Thanks for your Help ..!
Thivin D

**Comment by otacke** [comment]
@thivinanandh You can immediately derive from the alphabet used (not just hexadecimal characters) that it's not based on a UUID. I assume it's merely some random string and I'd have to look into the source code, too - I don't know every line of H5P code by name ;-)

**Comment by otacke** [comment]
@thivinanandh That random (or not so random) value is computed by PHP's `uniqid` function. 
Please cmp.
- https://github.com/h5p/h5p-editor-php-library/blob/53dc7bdc57b17f5a0d55a8871a36d1b1bd631e70/h5peditor-file.class.php#L204 for source and
- https://www.php.net/manual/en/function.uniqid.php for implementation details and
- https://github.com/Riamse/python-uniqid/blob/master/uniqid.py for a re-implementation in Python.

**Comment by thivinanandh** [comment]
Hi Oliver,

Thanks a Ton for your inputs. !
I will check them out and update the code base.

Thanks,
Thivin D
