### ISSUE TITLE
The program does not work, whether on windows or ubuntu

### ISSUE THREAD

**Issue by Nitr0z** [thivinanandh/pdf_to_h5p_converter#4]
The program does not work, whether on windows or ubuntu

Ubuntu : 
![image](https://user-images.githubusercontent.com/48621976/211281712-d2aba4d8-527e-49b7-979f-c2bc63bcab64.png)

Windows :
![image](https://user-images.githubusercontent.com/48621976/211281731-1a6fbd67-0f3a-4eaf-8951-083cd0f9e1a9.png)

It seems to come from a path problem.

Regards,
Théo

**Comment by thivinanandh** [comment]
Hi @Nitr0z 

The problem seems to appearing due to the changes we made for the webdeployment of the app. Now, the value of "webOutputDir" is added as "." by default. So the program will generate the final h5p file on the root directory of the code itself. 

Please check now, it should be working..!

If you like the idea, kindly share and star the project.!

**Comment by thierryforbGM** [comment]
I've the same issue but on the next line in code :) the programm doesn't work with parameters. It works without

python3 generateh5p.py Diaporama2.pdf --resolution 640
Traceback (most recent call last):
  File "/home/thierry/bin/PDFtoH5P/pdf_to_h5p_converter/generateh5p.py", line 90, in <module>
    p1 = subprocess.call(f'cp {webOutputdir}/{inputFileName} {imagePath}'.split(" ")) 
                               ^^^^^^^^^^^^
NameError: name 'webOutputdir' is not defined

**Comment by thierryforbGM** [comment]
Solved in modifying the code this way : line 50 

    else:
        webOutputdir = "."
        inputFileName = sys.argv[1]

If arguments are used, the resolution **and** dpi are necessary

**Comment by thivinanandh** [comment]
@thierryforbGM , thanks for the update.. 
I have updated the code now to handle default values for arguments.. Please use the newer version
